name: Build Leaderboard Image
run-name: Based on ${{ github.sha }}
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD Commit
        uses: actions/checkout@v4.1.1
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.12'

      - name: Install pipenv
        run: pip install pipenv

      - name: Export requirement.txt
        run: PIPENV_DONT_LOAD_ENV=1 pipenv requirements > requirements.txt

      - name: Export Docker Build Tag
        id: tag
        run: echo "value=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: DockerHub Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build and Push
        uses: docker/build-push-action@v5.1.0
        with:
          context: '.'
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/leaderboard:${{ steps.tag.outputs.value }}
